### ISSUE TITLE
def make_tome_block

### ISSUE THREAD

**Issue by jimmycv07** [lixirui142/VidToMe#4]
Hi, thank you for your great work! I'd like to ask about the `make_tome_block` function in the case where the diffuser pipeline is not used. Is it fully functional in the current version, or is it necessary for me to complete it myself?

**Comment by lixirui142** [comment]
Hi, 

`make_tome_block` does work now. It is inherited from the original ToMe codebase. As we conduct experiments with diffusers, we have not added support for other diffusion implementations.

Due to my schedule, I may not be able to fix it soon. However, you can follow `make_diffusers_tome_block` to complete it:

1. Copy your transformer forward code to make_tome_block.ToMeBlock.forward
2. Add compute_merge and unmerge operations before and after self-attention.

**Comment by jimmycv07** [comment]
Thank you so much for the prompt reply and for providing guidance on the implementation! I will definitely proceed with completing the implementation on my own.
